### ISSUE TITLE
Background beacon detection not working with iOS 15, which was working with iOS 14. 

### ISSUE THREAD

**Issue by alirazaethos** [RantmediaLimited/iBeacons#2]
I updated my iPhone to iOS 15 two days ago and background beacon detection has stopped working when app is closed. 
So If I walk into the beacon range with the app closed and "always" permission granted, app does not detect beacon region and does not show local notification. 

Any thoughts ?

**Comment by james-rant** [comment]
The code in this repo is over 4 years old, and iOS has changed significantly since it was written. I wouldn't recommend using this code as a basis for implementing iBeacons anymore. When this code was originally written the location permissions didn't have a concept of "Allow while in use" vs. "Allow Always", the only option was "Allow" or "Deny", and allowing would enable background location permissions as well. I believe this has changed again since iOS 15 where it will only present the options for "Allow Once" or "Allow while using app", both of which don't allow background usage. You will need to consult the latest documentation to see what needs to be done to obtain background location permission in the latest OS.
